
#
# This LookML file was generated by AtScale on 2025-11-13T13:54:49.644770044Z
#
# AtScale version: 2025.10.0
# Catalog: snowflake_usage_main

connection: "SE_DEMO_10"
label: "snowflake_usage_main"


include: "/views/snowflake_usage_main/snowflake_usage_model.view.lkml"


explore: snowflake_usage_model {
  label: "snowflake_usage_model"
}

